export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const EDIT_ANNOUNCEMENT = 'EDIT_ANNOUNCEMENT';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
